### PR TITLE
Fixing addTrackToPlayList

### PR DESCRIPTION
**Pull request by cool-acid**
... to correctly add an array of songs.
This fixes issue #63

### CODE REVIEW

**Comment by jamon** [comment]
Sorry, I haven't had time to work on this lately.  If someone else can pull and independently validate this still works, I'll merge it in.  Otherwise, I'll try to test it when I get a chance.

**Comment by limeblack** [comment]
bump

**Comment by cool-acid** [comment]
Until @jamon merges it, you can use my branch. I assure you it works fine. :)

**Comment by FunkeDope** [comment]
+1 this fixes the issue and doesn't appear to break anything else! thanks!

**Pull request merged**
